unit-mesh/auto-dev

src/main/kotlin/cc/unitmesh/devti/gui/chat/ChatCodingPanel.kt, src/main/kotlin/cc/unitmesh/devti/llms/openai/OpenAIProvider.kt
fix: openai setting change not affect in same project lifecycle 
fix: chat window loading will not be remove after request failed (for example openAI key invalid)
=> 设置在重新打开项目前不生效

src/main/kotlin/cc/unitmesh/devti/llms/openai/OpenAIProvider.kt
这个 PR 修复了使用 [one-api](https://github.com/songquanpeng/one-api) 作为 openai 代理时，获取响应内容引发数组越界异常，导致 auto-dev 对话无任何回应的问题
（可能是第三方实现差异？）[one-api](https://github.com/songquanpeng/one-api)  `/v1/chat/completions` 接口返回的首个 data 的 `choices` 会是空数组，这里简单对 `choices` 做一次判空以修复上述问题
```json5
data: {"id":"","object":"","created":0,"model":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"choices":[],"usage":null}
data: {"id":"chatcmpl-8Hl0aqEW4rt8jwDBQow9VAzU43pqB","object":"chat.completion.chunk","created":1699242968,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"role":"as …
```
=> fix: potential IndexOutOfBoundsException when streaming response

src/main/kotlin/cc/unitmesh/devti/gui/chat/ChatCodingPanel.kt, src/main/kotlin/cc/unitmesh/devti/gui/chat/MessageView.kt, src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomLLMProvider.kt, src/main/kotlin/cc/unitmesh/devti/llms/custom/JSONBodyResponseCallback.kt, src/main/kotlin/cc/unitmesh/devti/settings/Constants.kt, src/main/kotlin/cc/unitmesh/devti/settings/LLMSettingComponent.kt, src/test/kotlin/cc/unitmesh/devti/settings/LLMSettingComponentKtTest.kt
=> 支持 SSE 式 stream 返回和一次性 JSON 返回

src/main/kotlin/cc/unitmesh/devti/util/LLMCoroutineScope.kt
遇到过无任何出错提示，但对话不执行的情况。未能复现，但从 review 的代码看， 之前所用的 scope 是 EmptyContext，如果某个  coroutine 因异常退出而未被捕获，那会导致此 scope 被 cancel
=> fix: use SupervisorJob to prevent coroutine scope being cancel in all project lifetime

src/main/kotlin/cc/unitmesh/devti/llms/xianghuo/XingHuoProvider.kt, src/main/kotlin/cc/unitmesh/devti/settings/Constants.kt
close  #92 .
- Add Spark V3.5 support.
- Modify `XingHuoApiVersion` definition.
=> core: add Spark V3.5 support.

src/main/kotlin/cc/unitmesh/devti/llms/openai/OpenAIProvider.kt, src/main/kotlin/cc/unitmesh/devti/settings/AutoDevSettingsState.kt, src/main/kotlin/cc/unitmesh/devti/settings/Constants.kt, src/main/kotlin/cc/unitmesh/devti/settings/LLMSettingComponent.kt, src/main/resources/messages/AutoDevBundle.properties
=> core: add 'custom model' field for OpenAI API like.

docs/customize/custom-test-template.md
=> docs: fix typo in custom-test-template.md

docs/customize/custom-llm-server.md, src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomSSEProcessor.kt, src/main/kotlin/cc/unitmesh/devti/llms/openai/OpenAIProvider.kt
=> fix openAI custom model issue && add notice for wrong custom response format && updata documents

src/main/kotlin/cc/unitmesh/devti/custom/variable/SpecResolverService.kt
问题点：在idea配置中，修改setting文件中的Custom Engine Prompt(Json) 的内容后，重新发起Chat与模型沟通时，并未更新最新的JSON内容，需要重启IDEA，才可以重新加载。
修复后：可以更新JSON内容后，实时加载最新的JSON内容，解决需要重启才能刷新配置问题
=> bugfix：修复解决需要重启才能刷新Custom Engine Prompt(Json) 配置问题

src/main/kotlin/cc/unitmesh/devti/custom/CustomActionBaseIntention.kt, src/main/kotlin/cc/unitmesh/devti/custom/action/CustomIntentionConfig.kt
需求开发背景：我有一个提示词模板，但是相关的代码，在整个代码文件中，存在于多处，我不希望把所有的代码都一并上传，让大模型进行分析，那样提供的信息太多太杂，大模型分析的结果往往会受到干扰，生成的结果并不完美，因此我想考虑在选中内容时，有一个正则工具对提问的选择内容进行提前筛洗。
特性功能：在AutoDev的Custome Engine Prompt(Json) 中，属性：prompts 属性中， 增加属性：selectedRegex， 此属性表示标准正则表达式内容，用于在将选中的编辑器内容，进行正则匹配，将匹配的内容，筛选出来，如果有多个匹配符合，则会用 \n 隔开， 最后将匹配的内容，给予至模型调用方法
=> feat: 增加新特性，可以正则过滤编辑器选中的内容，提问内容更加精简，明确

src/main/kotlin/cc/unitmesh/devti/practise/RenameLookupManagerListener.kt
```kotlin
override fun activeLookupChanged(oldLookup: Lookup?, newLookup: Lookup?) {
if (!project.coderSetting.state.enableRenameSuggestion) return
val lookupImpl = newLookup as? LookupImpl ?: return
val editor = lookupImpl.editor as? EditorEx ?: return
val targetElement: PsiElement = lookupElement(lookupImpl, editor) ?: return
// maybe user just typing, we should handle for this
val originName = (targetElement as? PsiNameIdentifierOwner)?.name ?: return
if (originName.isBlank()) return
val promptText =
"$originName is a badname. Please provide 5 better options name for follow code: \n```${targetElement.language.displayName}\n${targetElement.text}\n```\n\n1."
try {
doExecuteNameSuggest(promptText, lookupImpl)
logger.warn("will trigger when typing from java code") // ======= Note here …
```
=> fix: wrong trigger when user typing from code.

src/main/kotlin/cc/unitmesh/devti/actions/chat/CodeCompleteChatAction.kt, src/main/kotlin/cc/unitmesh/devti/actions/groups/AutoChatDynamicActionGroup.kt, src/main/kotlin/cc/unitmesh/devti/gui/AutoDevToolWindowFactory.kt, src/main/kotlin/cc/unitmesh/devti/gui/chat/AutoDevInput.kt, src/main/kotlin/cc/unitmesh/devti/gui/chat/AutoDevInputSection.kt, src/main/kotlin/cc/unitmesh/devti/gui/chat/ChatCodingPanel.kt, src/main/kotlin/cc/unitmesh/devti/gui/chat/welcome/WelcomePanel.kt, src/main/kotlin/cc/unitmesh/devti/gui/toolbar/NewChatAction.kt, src/main/resources/messages/AutoDevBundle_en.properties, src/main/resources/messages/AutoDevBundle_zh.properties
1. After clicking stop, the progress bar is still visible
2. Multiple line breaks should not be able to be sent
3. Some actions are in progress, but the button is displayed as `Send`, such as `ExplainThisAction`,`RefactorThisAction`,`FixThisAction`
1.  Add a tooltip in the input box
2.  ToolwindowTitle, WelcomePanel, and Placeholder dynamically translate based on language changes
4.  After clicking on `New Chat`, clear the input box and add `WelcomePanel`
=> refactor: Optimized the components of the tool window

core/src/main/kotlin/cc/unitmesh/devti/settings/LLMSettingComponent.kt
```
Cannot create configurable
.....
Caused by: java.util.NoSuchElementException: Array contains no element matching the predicate.
at cc.unitmesh.devti.settings.LLMSettingComponent.get_currentSelectedEngine(LLMSettingComponent.kt:247)
at cc.unitmesh.devti.settings.LLMSettingComponent.getCurrentLLMParams(LLMSettingComponent.kt:82)
at cc.unitmesh.devti.settings.LLMSettingComponent.applySettings(LLMSettingComponent.kt:153)
at cc.unitmesh.devti.settings.LLMSettingComponent.applySettings$default(LLMSettingComponent.kt:123)
at cc.unitmesh.devti.settings.LLMSettingComponent.<init>(LLMSettingComponent.kt:241)
at cc.unitmesh.devti.settings.AutoDevSettingsConfigurable.<init>(AutoDevSettingsConfigurable.kt:10)
at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(C …
```
=> fix(LLMSettingComponent): 修复新装用户引擎未选择情况下的 `Array contains no element matching the predicate.` 异常

core/src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomSSEProcessor.kt
修正了在处理自定义字段时将所有值强制转换为 `jsonPrimitive` 的问题，改为直接使用字段值。这解决了某些复杂数据结构无法正确解析的问题。
这样允许类似如下的配置：
```json
{ "customFields": { "model":"qwen-plus", "stream": true, "stream_options": {"include_usage": true} }}
```
=> fix(CustomSSEProcessor): 支持自定义大模型 customFields 使用复杂类型字段

build.gradle.kts, core/src/main/kotlin/cc/unitmesh/devti/custom/document/CustomLivingDocTask.kt, core/src/main/kotlin/cc/unitmesh/devti/custom/tasks/FileGenerateTask.kt, core/src/main/kotlin/cc/unitmesh/devti/diff/DiffStreamHandler.kt, core/src/main/kotlin/cc/unitmesh/devti/gui/chat/ChatCodingService.kt, core/src/main/kotlin/cc/unitmesh/devti/inline/AutoDevInlineChatPanel.kt, core/src/main/kotlin/cc/unitmesh/devti/intentions/action/task/BaseCompletionTask.kt, core/src/main/kotlin/cc/unitmesh/devti/intentions/action/task/CodeCompletionTask.kt, core/src/main/kotlin/cc/unitmesh/devti/intentions/action/task/LivingDocumentationTask.kt, core/src/main/kotlin/cc/unitmesh/devti/intentions/action/task/TestCodeGenTask.kt, core/src/main/kotlin/cc/unitmesh/devti/llm2/ChatSession.kt, core/src/main/kotlin/cc/unitmesh/devti/llm2/LLMProvider2.kt, core/src/main/kotlin/cc/unitmesh/devti/llms/LlmFactory.kt, core/src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomLLMProvider.kt, core/src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomSSEProcessor.kt, core/src/main/kotlin/cc/unitmesh/devti/llms/custom/InlayCustomLLMProvider.kt, core/src/main/kotlin/cc/unitmesh/devti/practise/RenameLookupManagerListener.kt, core/src/main/kotlin/cc/unitmesh/devti/runconfig/AutoDevRunProfileState.kt, core/src/main/kotlin/cc/unitmesh/devti/settings/LLMSettingComponent.kt, core/src/main/kotlin/cc/unitmesh/devti/settings/TestConnection.kt, core/src/main/kotlin/cc/unitmesh/devti/settings/coder/AutoDevCoderConfigurable.kt, core/src/main/kotlin/cc/unitmesh/devti/util/AutoDevCoroutineScope.kt, core/src/test/kotlin/cc/unitmesh/devti/llm2/LLMProvider2Test.kt, exts/devins-lang/src/main/kotlin/cc/unitmesh/devti/language/run/DevInsRunConfigurationProfileState.kt, exts/ext-database/src/main/kotlin/cc/unitmesh/database/actions/AutoSqlAction.kt, exts/ext-git/src/main/kotlin/cc/unitmesh/git/actions/vcs/CommitMessageSuggestionAction.kt, exts/ext-terminal/src/main/kotlin/cc/unitmesh/terminal/ShellCommandSuggestAction.kt, java/src/main/kotlin/cc/unitmesh/idea/actions/AutoCrudAction.kt, javascript/src/main/kotlin/cc/unitmesh/ide/javascript/actions/AutoPageAction.kt
- Changed LlmFactory from a class to a singleton object to simplify instantiation.
- Updated all references to use LlmFactory.create() instead of LlmFactory() or LlmFactory.instance.create().
- Removed unnecessary project parameter from testLLMConnection().
- Added LLMProvider2 for improved LLM session management and testing.
=> refactor(llm): convert LlmProvider to non-singleton

core/src/main/kotlin/cc/unitmesh/devti/gui/chat/ChatCodingPanel.kt, core/src/main/kotlin/cc/unitmesh/devti/inline/AutoDevInlineChatPanel.kt, core/src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomSSEProcessor.kt, core/src/main/kotlin/cc/unitmesh/devti/settings/devops/AutoDevDevOpsConfigurableProvider.kt, core/src/main/kotlin/cc/unitmesh/devti/sketch/SketchInputListener.kt, core/src/main/kotlin/cc/unitmesh/devti/sketch/SketchToolWindow.kt
Sketch cannot be stopped, I have to wait for it to end, or close it, including inline chat and tool window, so interrupt handling is added to sketch.
=> feat(sketch): Add interrupt handling and process listeners

core/src/main/kotlin/cc/unitmesh/devti/inline/AutoDevInlineChatPanel.kt
Add EscHandler to manage editor escape events. Closes inline chat panel when pressing ESC without selection/multiple-carets, preserves default behavior otherwise. close #301
=> feat(inline-chat): handle ESC key to close panel

core/src/main/kotlin/cc/unitmesh/devti/inline/AutoDevInlineChatPanel.kt
Invert condition and use early return for better readability in execute method. This simplifies the code flow when handling multi-caret or selection scenarios.
=> refactor(inline): improve caret state handling logic

core/src/main/kotlin/cc/unitmesh/devti/mcp/host/AutoDevMcpTools.kt, core/src/main/kotlin/cc/unitmesh/devti/mcp/host/HostMCPService.kt, core/src/main/kotlin/cc/unitmesh/devti/mcp/host/McpParam.kt, core/src/main/kotlin/cc/unitmesh/devti/mcp/host/McpTool.kt
新增 McpParam 注解用于为 MCP 工具参数提供描述信息，并更新 PropertySchema 支持描述字段。这样可以让 MCP 客户端更好地理解工具参数的用途。
=> feat(mcp): 添加 McpParam 注解支持工具参数描述

core/src/main/kotlin/cc/unitmesh/devti/gui/chat/ui/AutoDevInput.kt
修复AutoDevInput中Enter键快捷键与IDE代码补全弹窗的冲突问题。通过监听LookupManagerListener动态注册/注销Enter键快捷键，确保补全弹窗显示时Enter键用于选择补全项，弹窗关闭时用于提交输入。
=> fix(input): 优化Enter键处理避免与代码补全冲突

build.gradle.kts, core/src/main/kotlin/cc/unitmesh/devti/mcp/client/CustomMcpServerManager.kt, core/src/main/kotlin/cc/unitmesh/devti/mcp/client/McpConfig.kt, core/src/main/kotlin/cc/unitmesh/devti/mcp/ui/McpConfigService.kt, core/src/test/kotlin/cc/unitmesh/devti/mcp/client/McpConfigTest.kt, docs/mcp-streamable-http.md, example/mcp/streamable-http-example.mcp.json
Upgrades the MCP kotlin-sdk dependency from 0.5.0 to 0.6.0 and prepares the foundation for HTTP transport support as requested in #429. This PR ensures the codebase builds successfully with the new SDK version while maintaining all existing functionality.
- Upgraded `io.modelcontextprotocol:kotlin-sdk` from `0.5.0` to `0.6.0`
- This version includes `StreamableHttpClientTransport` class needed for HTTP support
- Fixed `Tool` constructor parameters to match kotlin-sdk 0.6.0 API
- Updated `Tool` instantiation in `McpConfigService.kt` with correct parameter order
- All compilation errors resolved and build passes successfully
- Added optional `url` field to `McpServer` data class for future HTTP-based servers
- Made `command` field optional to support URL-only configurations
- Maintains full …
=> feat: Upgrade kotlin-sdk to 0.6.0 and prepare for HTTP transport support
